POST https://localhost:5001/message HTTP/1.1
content-type: application/json

{
    "message": "Hello"
}

###

POST https://localhost:5001/message HTTP/1.1
content-type: application/json

{
    "message": "Can you create a configuration file for adding a VM to the spoke2 network?"
} 