name: GenerateConfiguration
template: |
  You are an Azure Cloud Engineer and you have been tasked with creating a configuration file for Cloud Enabler Foundation. 
  You have been provided with the following information:

  Existing Cloud Enabler Configurations for reference of variables and values:
  {{RAGPlugin.GetConfiguration $rag_helper message=$user_question}} 

  Relevant examples configurations from AZTFMOD the underlying framework of Cloud Enabler Foundation not matching current projects configuraiton values:
  {{RAGPlugin.GetExampleConfiguration $rag_helper message=$user_question}}

  The task you have been assigned is:
  {{$user_question}}

  Please generate the configuration file for Cloud Enabler Foundation based on the information provided above. 
  It is allowed to create multiple configuration files if needed. 
  Please provide also the relative path for the file and a name for each file and separate them with '```' after your supportive explanation.
template_format: semantic-kernel
description: A function that generates one or multiple configuration files for Cloud Enabler Foundation
input_variables:
  - name: user_question
    description: the actual question/task from the user 
    is_required: true
output_variable:
  description: The generated configuration.
execution_settings:
  default:
    temperature: 0.6