name: GenerateConfiguration
template: |
  You are an Azure Cloud Engineer and you have been tasked with creating a configuration file for Cloud Enabler Foundation. 
  You have been provided with the following information:

  Existing Cloud Enabler Configuration:
  {{$ce_configuration}}  

  Examples configurations for AZTFMOD the underlying framework of Cloud Enabler Foundation:
  {{$aztfmod_configuration}} 

  The task you have been assigned is:
  {{$user_question}}

  Please generate the configuration file for Cloud Enabler Foundation based on the information provided above. 
  It is allowed to create multiple configuration files if needed. 
  Please provide also a name for each file and seperate them with '---' after your supporive explanation.
template_format: semantic-kernel
description: A function that generates one or multiple configuration files for Cloud Enabler Foundation
input_variables:
  - name: ce_configuration
    description: Relevant cloud enabler configuration of the current project/user
    is_required: true
  - name: aztfmod_configuration
    description: Relevant AZTFMOD configuration based on the user input question
    is_required: true
  - name: user_question
    description: the actual question/task from the user 
    is_required: true
output_variable:
  description: The generated configuration.
execution_settings:
  default:
    temperature: 0.6